use std::{collections::HashSet, fmt::Display, num::ParseIntError, ops::RangeInclusive};

use rand::seq::SliceRandom;

#[derive(PartialEq, Clone)]
pub enum NumberGeneration {
    Ordered(usize),
    ReverseOrdered(usize),
    Random {
        amount: usize,
        disorder: Option<RangeInclusive<f64>>,
    },
    RandomRanged {
        range: RangeInclusive<i64>,
        amount: usize,
        disorder: Option<RangeInclusive<f64>>,
    },
    Arbitrary(String),
    Preset(usize),
}

pub fn compute_disorder<T>(stack: &[T]) -> f64
where
    T: Ord,
{
    let mut mistakes = 0;
    let mut total_pairs = 0;
    for i in 0..(stack.len() - 1) {
        for j in (i + 1)..(stack.len() - 1) {
            total_pairs += 1;
            if stack[i] > stack[j] {
                mistakes += 1;
            }
        }
    }
    mistakes as f64 / total_pairs as f64
}

fn generate_with_disorder(disorder_range: RangeInclusive<f64>, mut numbers: Vec<i64>) -> Vec<i64> {
    let middle = (disorder_range.start() + disorder_range.end()) / 2.;
    if middle > 0.6666666666666666 {
        numbers.reverse();
    }
    while !disorder_range.contains(&compute_disorder(&numbers)) {
        let ra = rand::random_range(0..numbers.len());
        let rb = rand::random_range(0..numbers.len());
        numbers.swap(ra, rb);
    }
    numbers
}

impl NumberGeneration {
    pub fn get_numbers(&self) -> Result<Vec<i64>, ParseIntError> {
        match &self {
            NumberGeneration::Ordered(r) => Ok((0..(*r as i64)).collect()),
            NumberGeneration::ReverseOrdered(r) => Ok((0..(*r as i64)).rev().collect()),
            NumberGeneration::Random { amount, disorder } => Ok(match disorder {
                Some(d) => generate_with_disorder(d.clone(), (0..(*amount as i64)).collect()),
                None => {
                    let mut nums: Vec<_> = (0..(*amount as i64)).collect();
                    nums.shuffle(&mut rand::rng());
                    nums
                }
            }),
            NumberGeneration::RandomRanged {
                range,
                amount,
                disorder,
            } => {
                let mut map = HashSet::new();
                while map.len() < *amount {
                    map.insert(rand::random_range(range.clone()));
                }
                Ok(match disorder {
                    Some(d) => {
                        let mut vec: Vec<_> = map.into_iter().collect();
                        vec.sort();
                        generate_with_disorder(d.clone(), vec)
                    }
                    None => map.into_iter().collect(),
                })
            }
            NumberGeneration::Arbitrary(s) => s.split_whitespace().map(|s| s.parse()).collect(),
            NumberGeneration::Preset(i) => Ok(NUMBER_PRESETS[*i].1.to_vec()),
        }
    }
}

impl Display for NumberGeneration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match *self {
            NumberGeneration::Arbitrary(_) => "User Input",
            NumberGeneration::Random { .. } => "Random Normalized",
            NumberGeneration::RandomRanged { .. } => "Random from Custom Range",
            NumberGeneration::Ordered(_) => "Ordered",
            NumberGeneration::ReverseOrdered(_) => "Reverse Ordered",
            NumberGeneration::Preset(_) => "Preset",
        };
        write!(f, "{}", str)
    }
}

// NOTE: Presets generated by another 42 student, I do not ake credit for generating these
#[rustfmt::skip]
pub const NUMBER_PRESETS: &[(&str, &[i64])] = &[
    ("Pencil", &[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67, 65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]),
    ("Almost Pencil", &[2, 97, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 99, 4, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67, 65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]),
    ("Reverse Pencil", &[98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
    ("Reverse Steps", &[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 75, 76, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]),
    ("Double Reverse Steps", &[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 75, 76, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
    ("\"Thing\"", &[100, 33, 1, 99, 32, 2, 98, 31, 3, 97, 30, 4, 96, 29, 5, 95, 28, 6, 94, 27, 7, 93, 26, 8, 92, 25, 9, 91, 24, 10, 90, 23, 11, 89, 22, 12, 88, 21, 13, 87, 20, 14, 86, 19, 15, 85, 18, 16, 84, 17, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50]),
    ("3-Way Interlocked Ramp", &[150, 1, 152, 148, 3, 154, 146, 5, 156, 144, 7, 158, 142, 9, 160, 140, 11, 162, 138, 13, 164, 136, 15, 166, 134, 17, 168, 132, 19, 170, 130, 21, 172, 128, 23, 174, 126, 25, 176, 124, 27, 178, 122, 29, 180, 120, 31, 182, 118, 33, 184, 116, 35, 186, 114, 37, 188, 112, 39, 190, 110, 41, 192, 108, 43, 194, 106, 45, 196, 104, 47, 198, 102, 49, 200, 100, 51, 202, 98, 53, 204, 96, 55, 206, 94, 57, 208, 92, 59, 210, 90, 61, 212, 88, 63, 214, 86, 65, 216, 84]),
    ("2-Way Symetrical Interlocked Ramp", &[100, 1, 98, 3, 96, 5, 94, 7, 92, 9, 90, 11, 88, 13, 86, 15, 84, 17, 82, 19, 80, 21, 78, 23, 76, 25, 74, 27, 72, 29, 70, 31, 68, 33, 66, 35, 64, 37, 62, 39, 60, 41, 58, 43, 56, 45, 54, 47, 52, 49, 50, 51, 48, 53, 46, 55, 44, 57, 42, 59, 40, 61, 38, 63, 36, 65, 34, 67, 32, 69, 30, 71, 28, 73, 26, 75, 24, 77, 22, 79, 20, 81, 18, 83, 16, 85, 14, 87, 12, 89, 10, 91, 8, 93, 6, 95, 4, 97, 2, 99]),
    ("2-Way Decreasing Ramp", &[100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 101, 99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67, 65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]),
];
